Translation improvements to es.toml
rocky-linux/rockylinux.org-hugo pull request #126
Opened 2020-12-15 10:55 UTC by xerz-one

- Replaced "ascendente" terminology to "upstream"
  - Corrected "intermedio"/"descendente" as "downstream"
- Changed "ETA" to "fecha estimada"
- "Build" is translated as "versión" instead of "compilación"
- A bit of redundant language was replaced, as with "opciones de comunicación"

2020-12-15 11:03 UTC, Addvilz commented
> Replaced "ascendente" terminology to "upstream"
> Corrected "intermedio"/"descendente" as "downstream"

The best practice is to avoid anglicisms where possible.

> Que significa, \"¿Su socio downstream ha cambiado de dirección?\"

This is not correct. It's the upstream that has changed direction, not downstream. `ascendente` should be used here.

2020-12-15 11:42 UTC, domingoruiz approved these changes
I see it ok.

2020-12-15 20:46 UTC, xerz-one commented
@Addvilz On anglicisms: I understand your concern about non-native words, but I would consider "ascendente" and "descendente" not to be widespread terms for the concepts of upstream and downstraem as, at least myself, have never encountered the usage of any other terms for it in Spanish other than the English originals, thus "downstream" and "upstream" should be easier to understand for the expected audience for Rocky - it certainly took me reading the English version to check the meaning. Communication ease is the priority here, descriptivism over prescriptivism, at least as long as there is no consensus in a native word.

And in particular, the "socio downstream" part, if mistaken, is also mistaken in the English version of the page, since it's how it currently calls it on it (see [i18n/en.toml](https://github.com/rocky-linux/rockylinux.org/blob/9fed179bde0ebb5ccdc386c92b20bf5b473f32f8/i18n/en.toml#L72))

2020-12-16 00:23 UTC, migueldiez commented on i18n/es.toml
> +    other = "Que significa, \"¿Su socio downstream ha cambiado de dirección?\""
Incorrecta puntuación y falta tilde. Versión correcta:
"¿Qué significa, \"su socio downstream ha cambiado de dirección?\""

2020-12-16 00:30 UTC, migueldiez commented on i18n/es.toml
> +    other = "Entonces, ¿dónde entra en juego Rocky Linux?"
La tradución es muy forzada. Una forma más natural de decirlo con el espíritu del original sería:
"¿Cuál es el propósito de Rocky Linux?"

2020-12-16 00:41 UTC, migueldiez commented on i18n/es.toml
> +    other = "El proyecto CentOS anunció recientemente un cambio en la estrategia de CentOS. Mientras que anteriormente CentOS existía como una versión downstream de su proveedor upstream (recibe parc
Varios cambios:
"... en la estrategia para CentOS."

", se cambiará a una" -> ", ahora cambiará a una"

Incorrecto, el soporte no se ha interrumpido, sino que se ha acortado:
"Además, el soporte para CentOS Linux 8 se ha acortado, "
y las fechas las suelo ver en diversos documentos en formato estandard, tanta letra hace más dificil la lectura y la comparación. 
"desde el 31 de mayo de 2029 hasta el 31 de diciembre de 2021." -> "desde el 2029-05-31 hasta el 2021-12-31."

2020-12-16 00:42 UTC, migueldiez reviewed
.

2020-12-16 00:43 UTC, migueldiez requested changes
En general muchas experisones son incorrectas o poco naturales.

He incluido algunas sugerencias

2020-12-16 00:47 UTC, migueldiez approved these changes
The added changes are correct.

I have suggested other changes that are not related with your commit. Maybe for other commit.

2020-12-16 09:10 UTC, Addvilz commented
> @Addvilz On anglicisms: I understand your concern about non-native words, but I would consider "ascendente" and "descendente" not to be widespread terms for the concepts of upstream and downstream as, at least myself, have never encountered the usage of any other terms for it in Spanish other than the English originals, thus "downstream" and "upstream" should be easier to understand for the expected audience for Rocky - it certainly took me reading the English version to check the meaning. Communication ease is the priority here, descriptivism over prescriptivism, at least as long as there is no consensus in a native word.
> 
> And in particular, the "socio downstream" part, if mistaken, is also mistaken in the English version of the page, since it's how it currently calls it (see [i18n/en.toml](https://github.com/rocky-linux/rockylinux.org/blob/9fed179bde0ebb5ccdc386c92b20bf5b473f32f8/i18n/en.toml#L72)). The "downstream partner" being referred to there is CentOS, not RHEL.

This argument would be valid for technical documentation and purpose written text where domain knowledge is implied as mandatory anyway. This is a somewhat generic landing page anyone with or **without** domain knowledge can visit, and we are required to consider that while localizing. And just because you understand those terms, and that is your personal experience, it does not mean at all everyone will - considering that even in English, upstream and downstream are obscure technical terms most English speakers associate with aquatic navigation, not engineering.

2020-12-16 16:48 UTC, ressonix commented
Right, I think we'll convert this to a draft for now since there is some translation disputes. Feel free to mark as ready for review when we've come to a conclusion on what should happen, or alternatively close the PR if we feel that no changes are necessary at this time.

2020-12-16 19:10 UTC, XescoAlarcon commented on i18n/es.toml
> +    other = "Que significa, \"¿Su socio downstream ha cambiado de dirección?\""
Estoy de acuerdo pero yo incluiría las comillas dobles dentro de la pregunta, además a nivel de sintaxis no separaría predicado verbal de sujeto, esto es:

"**¿Qué significa "su socio downstream ha cambiado de dirección"?**"

De todas formas no sé si el uso de las comillas sería el más adecuado para una cita:

"**¿Cuál es el significado de  «su socio downstream ha cambiado de dirección»?**"

2020-12-16 22:52 UTC, ressonix commented
Closing this PR in favor of #138, based on suggestions in this discussion. If you have further improvement suggestions, feel free to open another PR.

2020-12-16 22:52 UTC, closed without merging