Improve french translation
rocky-linux/rockylinux.org-hugo pull request #164
Opened 2020-12-19 17:35 UTC by Ninroot

Slight improvement in the translation.

2020-12-20 11:44 UTC, SergeCroise requested changes

2020-12-20 11:44 UTC, SergeCroise commented on i18n/fr.toml
> +    other = "Le projet CentOS a récemment annoncé un changement de stratégie. Alors que CentOS existait auparavant en tant que version en aval de son fournisseur (elle reçoit les correctifs et les mi
... (elle reçoit les correctifs et les mises à jour après que le fournisseur en amont ne le fasse)...

2020-12-20 17:51 UTC, SergeCroise approved these changes

2020-12-21 08:16 UTC, domingoruiz approved these changes
I see it ok. Very Good.

Thanks

2020-12-21 09:28 UTC, hbjydev commented
I'm now at a point where I don't want to accept any more i18n PRs, simply because it's going to become FAR too unmaintainable, so I'm going to prioritise #134 and close this PR.

2020-12-21 09:28 UTC, closed without merging