Updated the Swedish translation to sound more natural
rocky-linux/rockylinux.org-hugo pull request #165
Opened 2020-12-19 23:23 UTC by cascading-jox

The latest translation of the Swedish text that was merged was better than the last one but it still did not sound like something you would say in Swedish. I updated the translation once more with more commonly used English words instead of the literal translated words, restructured some sentences and made it overall sound more natural. I would appreciate some feedback from some Swedish talking people. 👍/👎?

2020-12-20 14:50 UTC, SergeCroise commented on i18n/sv.toml
> +    other = "Vad menas med att \"downstream-partnern har bytt inriktning?\""
other = "Vad menas med att \"downstream-partnern har bytt inriktning\"?"

2020-12-20 15:10 UTC, bittin commented on i18n/sv.toml
> +  other = "© 2020 Rocky Linux projektet. Alla rättigheter förbehållna."
Looks good

2020-12-20 15:10 UTC, bittin commented on i18n/sv.toml
> +  other = "CentOS är ett registrerat varumärke som tillhör Red Hat, Inc. Rocky Linux projektet är inte anknutet till eller godkänt av Red Hat, Inc."
Looks good

2020-12-20 15:10 UTC, bittin commented on i18n/sv.toml
> +    other = "Sidan du försökte nå kunde inte hittas. Var god försök igen."
Looks good

2020-12-20 15:11 UTC, bittin commented on i18n/sv.toml
> +  other = "En community-driven insats för att skapa en enterprise-klassad linuxdistribution redo att användas i skarp drift."
"En gemenskapsdriven insats för att skapa en enterprise-klassad linuxdistribution redo att användas i skarp drift."
Yeah enterprise-klassad och företagsklassad not sure whats best?

2020-12-20 15:11 UTC, bittin commented on i18n/sv.toml
> +  other = "Vad är Rocky Linux projektet?"
Looks good

2020-12-20 15:12 UTC, bittin commented on i18n/sv.toml
> +  other = "Rocky Linux är ett community-drivet enterprise-operativsystem designat för att vara 100% bugg-för-bugg kompatibelt med Amerikas främsta enterprise-klassade linuxdistribution nu när downstr
Gemenskapsdriven is more correct Swedish also not sure if Enterprise or Företag is best?

2020-12-20 15:14 UTC, bittin reviewed
Did a review of it now

2020-12-20 15:14 UTC, bittin commented on i18n/sv.toml
> +[faq]
*Approve*

2020-12-20 15:14 UTC, bittin commented on i18n/sv.toml
> +    other = "Vad menas med att \"downstream-partnern har bytt inriktning?\""
Looks good

2020-12-20 15:14 UTC, bittin commented on i18n/sv.toml
> +    other = "Så var kommer Rocky Linux in i bilden?"
Looks good

2020-12-20 15:14 UTC, bittin commented on i18n/sv.toml
> +    other = "CentOS-projektet tillkännagav nyligen att de har bytt strategi för CentOS. Tidigare existerade CentOS som en downstream build från upstream vendorn (den tar emot patcher och uppdateringa
Looks good

2020-12-20 15:14 UTC, bittin commented on i18n/sv.toml
> +    other = "Målet med Rocky Linux är att fungera som en downstream build som CentOS tidigare gjorde, där releaser byggdes efter de har lagts till av upstream vendorn, inte före."
Looks good

2020-12-20 15:16 UTC, bittin commented
Did a review now

On Sun, Dec 20, 2020 at 3:51 PM Serge Croisé <notifications@github.com>
wrote:

> *@SergeCroise* commented on this pull request.
> ------------------------------
>
> In i18n/sv.toml
> <https://github.com/rocky-linux/rockylinux.org/pull/165#discussion_r546387001>
> :
>
> >    [faq.title]
>
>    other = "Vanliga frågor"
>
>
>
>    [faq.q]
>
>      [faq.q.downstream-partner-direction]
>
> -    other = "Vad menar ni med att \"dess nedströmspartner har skiftat riktning?\""
>
> +    other = "Vad menas med att \"downstream-partnern har bytt inriktning?\""
>
>
> other = "Vad menas med att "downstream-partnern har bytt inriktning"?"
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/rocky-linux/rockylinux.org/pull/165#pullrequestreview-556024341>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAAKRPP7QVKNIWF2KZKQF23SVYFMHANCNFSM4VCULLZQ>
> .
>

2020-12-20 15:33 UTC, cascading-jox commented on i18n/sv.toml
> +  other = "En community-driven insats för att skapa en enterprise-klassad linuxdistribution redo att användas i skarp drift."
I have never heard the word företagsklass and I don't know what it means. Rewriting it like this "klass för företag" maybe makes my confusion more obvious. What do you think?

2020-12-20 15:44 UTC, cascading-jox commented on i18n/sv.toml
> +  other = "Rocky Linux är ett community-drivet enterprise-operativsystem designat för att vara 100% bugg-för-bugg kompatibelt med Amerikas främsta enterprise-klassade linuxdistribution nu när downstr
I guess it's a matter of taste. Maybe I'm turning into an anglo-saxon but I think community makes more sense than gemenskap, in software development at least. I believe gemenskap would be more equal to fellowship.

2020-12-20 19:18 UTC, SergeCroise commented on i18n/sv.toml
> +    other = "Vad menas med att \"downstream-partnern har bytt inriktning?\""
other = "Vad menas med att \"downstream-partnern har bytt inriktning\\"?"

2020-12-20 19:19 UTC, SergeCroise requested changes

2020-12-20 19:19 UTC, SergeCroise commented on i18n/sv.toml
> +    other = "Vad menas med att \"downstream-partnern har bytt inriktning?\""
other = "Vad menas med att \"downstream-partnern har bytt inriktning\\"?"

2020-12-20 19:20 UTC, bittin commented on i18n/sv.toml
> +    other = "Vad menas med att \"downstream-partnern har bytt inriktning?\""
> other = "Vad menas med att "downstream-partnern har bytt inriktning\"?"

even better

2020-12-21 09:28 UTC, hbjydev commented
I'm now at a point where I don't want to accept any more i18n PRs, simply because it's going to become FAR too unmaintainable, so I'm going to prioritise #134 and close this PR.

2020-12-21 09:28 UTC, closed without merging