added Georgian (ka) translation
rocky-linux/rockylinux.org-hugo pull request #35
Opened 2020-12-12 18:54 UTC by GioMac

2020-12-12 19:05 UTC, ressonix commented
Please update `config.toml`, `vercel.json`, and `layouts/partials/head/head.html` with your language. There are examples already in the files for you to reference.

2020-12-12 19:05 UTC, domingoruiz commented
The language definition is missing in config.toml, vercel.json and in the javascript of layouts/partials/head/head.html

2020-12-12 19:27 UTC, ressonix commented
@GioMac Here's a wiki link for reference, as well: https://wiki.rockylinux.org/en/Web/Website/contrib-i18n

2020-12-12 19:54 UTC, GioMac commented
@domingoruiz @ressonix thanks for doc
how do we set weight values? it's missing in doc, also, i think, it's better to include information about branch too (devel first?)

2020-12-12 20:02 UTC, ressonix commented
@GioMac I think the best way to do the weights is to look at the current total number of languages, +1 it, and if needed, one of us can change it if there would be conflicts on that front.

2020-12-12 20:03 UTC, ressonix commented
Regarding the branch, that's not a huge deal, we can edit the PR, but I'll definitely let Hayden know.

2020-12-12 20:04 UTC, fabaff commented
Related #33

2020-12-12 23:00 UTC, ressonix commented
Converted to draft until the rest of the setup is finished. ;)

2020-12-18 08:17 UTC, SergeCroise requested changes

2020-12-18 08:17 UTC, SergeCroise commented on i18n/ka.toml
> +    other = "რას ნიშნავს, \"ქვემდგომმა პარტნიორმა შეიცვალა მიმართულება?\""
მიმართულება\"?"

2020-12-21 09:29 UTC, hbjydev commented
I'm now at a point where I don't want to accept any more i18n PRs, simply because it's going to become FAR too unmaintainable, so I'm going to prioritise #134 and close this PR.

2020-12-21 09:29 UTC, closed without merging