Added Brazilian Portuguese support
rocky-linux/rockylinux.org-hugo pull request #41
Opened 2020-12-12 21:59 UTC by enmanuelmoreira

2020-12-12 22:51 UTC, ressonix requested changes
We need to differentiate the Brazilian Portuguese from general Portuguese (there's another PR for it), so I need you to change the language name in `config.toml` and `layouts/partials/head/head.html` to reflect the differences. Maybe something like "Portuguese (Brazil)"?

2020-12-12 23:02 UTC, GiovanniSM20 requested changes
I think that this file needs to be thoroughly revised before it can be accepted in addition to certain words needing other speakers to reach a translation agreement - not that they have different meanings but to "make sense" when they are read

2020-12-12 23:02 UTC, giovannism20 commented on i18n/pt_BR.toml
> +  other = "Um esforço da comunidade esfuerzo para obter um sistema Linux de classe empresarial pronto para produção."
you ended up repeating words in other languages in the translation. it would be better "Um esforço conduzido pela comunidade para obter..."

2020-12-12 23:02 UTC, giovannism20 commented on i18n/pt_BR.toml
> +  other = "O qué é o projeto Rocky Linux?"
more accent "O que é..."

2020-12-12 23:02 UTC, giovannism20 commented on i18n/pt_BR.toml
> +  other = "O Rocky Linux é um sistema operacional empresarial comunitário desenhado para ser 100% compatible com a distrubuição de Linux empresarial mais importante dos Estados Unidos agora que o sóc
you forgot to translate "compatible" word - compatível

2020-12-12 23:02 UTC, giovannism20 commented on i18n/pt_BR.toml
> +  other = "Perguntas frecuentes"
you forgot to translate "frequent/frecuentes" with correct word - frequentes

2020-12-12 23:02 UTC, giovannism20 commented on i18n/pt_BR.toml
> +    other = "O qué significa, \"¿O sócio anterior tinha trocado de direção?\""
you forgot to phrase - "O que você quer dizer com, \"seu parceiro de negócio mudou de direção ?\""

2020-12-12 23:02 UTC, giovannism20 commented on i18n/pt_BR.toml
> +  other = "Escolher idioma..."
you forgot the connective - "Escolha o idioma..."

2020-12-12 23:02 UTC, giovannism20 commented on i18n/pt_BR.toml
> +    other = "O projeto CentOS anunciou recentemente uma mudança na estratégia de CentOS. Anteriormente o CentOS existia como uma compilação descendente do seu fornecedor ascendente (recebe parches e
can be better translated:

O projeto CentOS anunciou recentemente uma mudança na estratégia do CentOS. Considerando que o CentOS existia anteriormente como um _build_ não "principal" de seu fornecedor "principal" (ou seja, ele recebe _patches_ e atualizações após o fornecedor "principal"), ele mudará para um _build_ "principal" (testes de _patches_ e atualizações antes da inclusão no fornecedor "principal"). Além disso, o suporte para CentOS Linux 8 foi interrompido, de 31 de maio de 2029 a 31 de dezembro de 2021. - i'm little bit suspect of the last phrase.

2020-12-12 23:02 UTC, giovannism20 commented on i18n/pt_BR.toml
> +    other = "Rocky Linux aponta a funcionar como uma compilação descendente como havía feito CentOS anteriormente, construíndo versões depois que tinham sido anadidas pelo fornecedor ascendente, não
can be better translated:

O Rocky Linux tem como objetivo funcionar como um _build_ não principal como o CentOS fazia anteriormente, criando _releases_ depois de serem adicionados pelo fornecedor "principal" e não antes.

2020-12-12 23:10 UTC, ressonix commented
Thanks for the input here @GiovanniSM20. I think we'll convert this into a draft until you guys have reached an agreement on the translations.

2020-12-12 23:58 UTC, enmanuelmoreira commented
Corregidas as traduções, acontece que eu traduzí do espanhol para portugués e algumas frases en esp tem outro sentido em pt

Muito obrigado @GiovanniSM20!

2020-12-13 01:20 UTC, enmanuelmoreira commented
It's ready to be checked and merge :)

2020-12-13 04:16 UTC, GiovanniSM20 commented
> It's ready to be checked and merged :)

It's not read yet and need too much changes.

2020-12-13 04:25 UTC, GiovanniSM20 commented
This will probably conflict with the current translation we have with Portuguese from Portugal (pt) instead of the Portuguese we use for Brazil pt-br.

2020-12-13 04:36 UTC, pxdnbluesoul commented
Not yet ready, please clear up the merge conflicts and try to fit the needed changes in stylistically. Let's make sure if we are offering both Portuguese and Brazilian Portuguese that they are easy to tell apart at a glance from the reader.

2020-12-13 04:43 UTC, GiovanniSM20 requested changes

2020-12-13 04:43 UTC, GiovanniSM20 commented on i18n/pt_BR.toml
> +other = "pt"
pt-br instead of only pt

2020-12-13 04:43 UTC, GiovanniSM20 commented on i18n/pt_BR.toml
> +  other = "O Rocky Linux é um sistema operacional empresarial comunitário desenhado para ser 100% compatível com a distrubuição de Linux empresarial mais importante dos Estados Unidos agora que o sóc
O Rocky Linux é um sistema operacional empresarial comunitário desenhado para ser 100% compatível com a distribuição Linux empresarial mais importante dos Estados Unidos agora que o sócio intermediário trocou de direção. Está em desenvolvimento intenso por parte da comunidade. O Rocky Linux é liderado por Gregory Kurtzer, fundador do projeto CentOS. Não há uma data para liberação. Solicitamos aos colaboradores que se comuniquem com as opções de comunicação que oferecemos no site.

No pr #44 preferimos traduzir o termo "ETA" dito que isso é um termo inglês que significa: estimated time of arrival.

2020-12-13 11:58 UTC, ressonix requested changes

2020-12-13 11:58 UTC, ressonix commented on layouts/partials/head/head.html
>          if(getParameterByName("l") == "Portuguese") {
Change "Portuguese" to "pt-BR"

2020-12-13 11:58 UTC, ressonix commented on layouts/partials/head/head.html
> +        if (language == "pt") {
Change "pt" to "pt-BR"

2020-12-13 11:58 UTC, ressonix requested changes

2020-12-13 11:58 UTC, ressonix commented on i18n/pt_BR.toml
> +other = "pt"
Correct! It should be "pt-BR"

2020-12-13 11:59 UTC, ressonix requested changes

2020-12-13 11:59 UTC, ressonix commented on vercel.json
> +    { "src": "/pt/(.*)", "status": 404, "dest": "/pt/404.html" },
Change pt to pt-BR

2020-12-13 12:41 UTC, ressonix approved these changes

2020-12-13 12:43 UTC, enmanuelmoreira commented
the requested changes have been made

2020-12-13 12:51 UTC, ressonix approved these changes

2020-12-13 14:50 UTC, merged