Add portuguese language support.
rocky-linux/rockylinux.org-hugo pull request #44
Opened 2020-12-12 22:36 UTC by dmarmelo

Add portuguese language support #33.

2020-12-12 23:06 UTC, GiovanniSM20 reviewed
this translation is very artificial and it really seems to have passed simply through the google translator but even better than the #41

2020-12-12 23:31 UTC, GiovanniSM20 approved these changes
.

2020-12-12 23:31 UTC, GiovanniSM20 commented on i18n/pt.toml
> +  other = "O Rocky Linux é um sistema operativo empresarial comunitário desenhado para ser 100% compatível com a distribuição de Linux empresarial mais importante dos Estados Unidos agora que o seu p
"sistema operacional" - instead of "sistema operativo".

"com a distribuição linux empresarial mais importante dos Estados Unidos" - i think the current one is not concise.

"Não existe data para um lançamento." - ETA is estimated time of arrival i think is better to put the therm translated instead of original term.

2020-12-12 23:34 UTC, GiovanniSM20 approved these changes

2020-12-12 23:35 UTC, GiovanniSM20 requested changes
I think that for now after the corrections are good if they are changed but later we will need to fix and agree on some terms :octocat:

2020-12-12 23:44 UTC, dmarmelo commented on i18n/pt.toml
> +  other = "O Rocky Linux é um sistema operativo empresarial comunitário desenhado para ser 100% compatível com a distribuição de Linux empresarial mais importante dos Estados Unidos agora que o seu p
This is a portuguese from portugal translation, and here we say "sistema operativo".
"com a distribuição linux empresarial mais importante dos Estados Unidos" - I don't like this sentence either but it is according to the spanish translation that is already online.
I already fixed the ETA.

2020-12-12 23:51 UTC, GiovanniSM20 commented on i18n/pt.toml
> +  other = "O Rocky Linux é um sistema operativo empresarial comunitário desenhado para ser 100% compatível com a distribuição de Linux empresarial mais importante dos Estados Unidos agora que o seu p
uhm, alright. I would like to apologize because I didn't pay attention to pt-portuguese

2020-12-12 23:51 UTC, GiovanniSM20 approved these changes
that's okay!

2020-12-12 23:54 UTC, dmarmelo commented on i18n/pt.toml
> +  other = "O Rocky Linux é um sistema operativo empresarial comunitário desenhado para ser 100% compatível com a distribuição de Linux empresarial mais importante dos Estados Unidos agora que o seu p
No problem 🙂

2020-12-13 01:14 UTC, ressonix approved these changes
I updated some things that were recently changed, but it looks good to go now!

2020-12-13 03:42 UTC, hbjydev approved these changes

2020-12-13 03:56 UTC, merged