Adding Swedish Translation
rocky-linux/rockylinux.org-hugo pull request #56
Opened 2020-12-13 11:04 UTC by bittin

Added Swedish Webpage Translation 

Added Swedish (Svenska) Translation 1.0 for the webpage

2020-12-13 11:06 UTC, ressonix commented
Converting this to a draft until all files have been implemented here. You can refer to the wiki to see what files are required for translations: https://wiki.rockylinux.org/en/Web/Website/contrib-i18n

2020-12-13 11:13 UTC, bittin commented
> Converting this to a draft until all files have been implemented here. You can refer to the wiki to see what files are required for translations: https://wiki.rockylinux.org/en/Web/Website/contrib-i18n

Have done this now, not sure about step 3 however as i haven't worked that much with hugo, but done step 2 and 4

2020-12-13 11:31 UTC, ressonix requested changes

2020-12-13 11:31 UTC, ressonix commented on config.toml
> +  baseURL = "/"
Small nitpick here, but can we remove the space before this line?

2020-12-13 11:31 UTC, ressonix commented on config.toml
> +      languageName = "Svenska"
Also here, let's make this line's indentation line up with the lines below.

2020-12-13 11:31 UTC, ressonix approved these changes
Once the requested changes are made it should be good to go (I accidentally approved them, so you can ignore this)

2020-12-13 11:36 UTC, ressonix commented
I went ahead and resolved some stuff for you, but this should now be good to go. I'll get Hayden to review so he can make a deployment.

2020-12-13 11:37 UTC, bittin commented on config.toml
> +      languageName = "Svenska"
Uploaded a fixed file, thanks :) :+1: 
i don't do much Github PRs so i am kinda new to it, but learned as i went

2020-12-13 14:23 UTC, joacimmelin commented
This translation is not very well written and should have been proof read by someone before publishing it.

2020-12-13 14:25 UTC, ressonix commented
@joacimmelin It hasn't been merged yet, so it hasn't been published. Feel free to make suggestions to @bittin.

2020-12-13 14:28 UTC, ressonix commented
I'll go ahead and make this PR a draft until you can resolve the translation disputes.

2020-12-13 14:32 UTC, bittin commented
@joacimmelin go ahead and make changes not sure how to translate all words in to good Swedish, i mostly wrote up something fast

2020-12-13 20:58 UTC, xevz requested changes
Mostly Swedish grammar related fixes.

2020-12-13 20:58 UTC, xevz commented on i18n/sv.toml
> +  other = "© 2020 The Rocky Linux Projektet. Alla rättigheter förbehållna."
```suggestion
  other = "© 2020 Rocky Linux-projektet. Alla rättigheter förbehållna."
```
Or maybe just keep it as "The Rocky Linux Project" since that's it's name, other translations have handled it differently.

2020-12-13 20:58 UTC, xevz commented on i18n/sv.toml
> +    other = "sidan hittas inte."
```suggestion
    other = "Sidan hittas inte."
```

2020-12-13 20:58 UTC, xevz commented on i18n/sv.toml
> +  other = "CentOS är ett rregistrerat varumärke av Red Hat, Inc. The Rocky Linux projektet är inte anslutet till, och inte heller godkänt av Red Hat, Inc."
```suggestion
  other = "CentOS är ett registrerat varumärke av Red Hat, Inc. The Rocky Linux-projektet är inte anslutet till, och inte heller godkänt av Red Hat, Inc."
```

2020-12-13 20:58 UTC, xevz commented on i18n/sv.toml
> +  other = "Vad är Rocky Linux Projektet?"
```suggestion
  other = "Vad är Rocky Linux-projektet?"
```

2020-12-13 20:58 UTC, xevz commented on i18n/sv.toml
> +    other = "CentOS projektet annonserade nyligen ett skifte i strategi för CentOS. Medan CentOS tidigare existerade som ett nedströmsbygge av dess uppströmsleverantör (det tar emot korrigeringar och
```suggestion
    other = "CentOS-projektet annonserade nyligen ett skifte i strategi för CentOS. Medan CentOS tidigare existerade som ett nedströmsbygge av dess uppströmsleverantör (det tar emot korrigeringar och uppdateringar eftersom att uppströmsleverantören gör det), det kommer att flyttas till att bara bli ett uppströmsbygge (testa korrigeringar och uppdateringar innan de införs hos uppströmsleverantören)). Dessutom, har stödet för CentOS Linux 8 förkortats, från Maj 31, 2029 till December 31, 2021."
```

2020-12-13 20:58 UTC, xevz commented on i18n/sv.toml
> +  other = "Rocky Linux är ett gemenskapsdrivet oprativsystem för företag och privatpersoner designat för att vara 100% bugg-för-bugg kompatibelt med Amerika's topp företags Linux distribution nu när
```suggestion
  other = "Rocky Linux är ett gemenskapsdrivet oprativsystem för företag och privatpersoner designat för att vara 100% bugg-för-bugg-kompatibelt med Amerikas främsta företags-Linux distribution nu när dess nedströms partner har ändrat inriktning. Det är under intensiv utveckling av gemenskapen. Rocky Linux leds av Gregory Kurtzer, grundare av CentOS-projektet. Det finns inget datum satt för första utgåvan. Bidragsgivare uppmanas att nå oss med hjälp av de kommunikationsalternativ som erbjuds på denna webbplats."
```

2020-12-13 22:01 UTC, Millnert reviewed
Mostly good, one change suggested.

2020-12-13 22:01 UTC, Millnert commented on i18n/sv.toml
> +    other = "CentOS projektet annonserade nyligen ett skifte i strategi för CentOS. Medan CentOS tidigare existerade som ett nedströmsbygge av dess uppströmsleverantör (det tar emot korrigeringar och
```suggestion
    other = "CentOS-projektet annonserade nyligen ett skifte i strategi för CentOS. Medan CentOS tidigare existerade som ett nedströmsbygge av dess uppströmsleverantör (det tar emot korrigeringar och uppdateringar eftersom att uppströmsleverantören gör det), det kommer att flyttas till att bara bli ett uppströmsbygge (testa korrigeringar och uppdateringar innan de införs hos uppströmsleverantören)). Dessutom, har stödet för CentOS Linux 8 förkortats, från 31:a maj, 2029 till 31:a december, 2021."
```

2020-12-13 22:01 UTC, Millnert commented on i18n/sv.toml
> +    other = "CentOS projektet annonserade nyligen ett skifte i strategi för CentOS. Medan CentOS tidigare existerade som ett nedströmsbygge av dess uppströmsleverantör (det tar emot korrigeringar och
The dates are not in proper Swedish format there. I sent a second review below which fixes those.

2020-12-14 05:35 UTC, xevz commented on i18n/sv.toml
> +  other = "Rocky Linux är ett gemenskapsdrivet oprativsystem för företag och privatpersoner designat för att vara 100% bugg-för-bugg kompatibelt med Amerika's topp företags Linux distribution nu när
I don't like the "gemenskapen" here though, but last night I couldn't really come up with a beter wording. "under intensiv utveckling av frivilliga" maybe?

2020-12-14 09:07 UTC, christiannageby requested changes
Some small points to make the text not seem so google translated.

2020-12-14 09:07 UTC, christiannageby commented on i18n/sv.toml
> +  other = "Gå med i diskussionen"
I would suggest Deltag i diskussionen,

```suggestion
  other = "Deltag i diskussionen"
```

2020-12-14 09:07 UTC, christiannageby commented on i18n/sv.toml
> +    other = "Den begärda resursen kunde inte hittas. Var god försök igen."
```suggestion
    other = "Den efterfrågade sidan hittades inte. Var god försök igen."
```

2020-12-14 09:07 UTC, christiannageby commented on i18n/sv.toml
> +    other = "CentOS projektet annonserade nyligen ett skifte i strategi för CentOS. Medan CentOS tidigare existerade som ett nedströmsbygge av dess uppströmsleverantör (det tar emot korrigeringar och
```suggestion
    other = "CentOS projektet tillkännagav nyligen ett skifte i strategi för CentOS. Medan CentOS tidigare existerade som ett nedströmsbygge av dess uppströmsleverantör (det tar emot korrigeringar och uppdateringar eftersom att uppströmsleverantören gör det), det kommer att flyttas till att bara bli ett uppströmsbygge (testa korrigeringar och uppdateringar innan de införs hos uppströmsleverantören). Dessutom, har stödet för CentOS 8 förkortats, från Maj 31, 2029 till December 31, 2021."
```

2020-12-14 10:51 UTC, migueldiez commented on i18n/sv.toml
> +  other = "Rocky Linux är ett gemenskapsdrivet oprativsystem för företag och privatpersoner designat för att vara 100% bugg-för-bugg kompatibelt med Amerika's topp företags Linux distribution nu när
What do you think about "...under intensiv utveckling av Rocket Linux samhället" ? (It's not a "förening").

2020-12-14 17:05 UTC, bittin commented
Accepted and Reviewed some of the translation fixes

2020-12-16 13:20 UTC, cascading-jox commented
I think the translations are correct but most technical terms sounds like nonsense in Swedish. It is just literal translations and it is difficult to understand, for me at least, because to my knowledge there is no literature or information online that people use with this terminology. Maybe it would be better to use the English technical terms in combination with Swedish? That is how people talk in real life so maybe it makes more sense than this?

2020-12-18 17:20 UTC, ressonix commented
Closing this one since @migueldiez seems to have taken over the progress in #150

2020-12-18 17:20 UTC, closed without merging